version: "3.2"
services:
  server:
    build: .
    command: dev_server
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"
      - "5678:5678"
    working_dir: /extension
    volumes:
      - $PWD:/extension
      - home_cache:/home/redash/.cache:delegated
      - client_dist:/app/client/dist:delegated
      - python_local:/home/redash/.local:delegated
      - node_modules:/app/node_modules:delegated
    environment:
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_BACKEND: "http://server:5000"
      REDASH_RATELIMIT_ENABLED: "false"
      REDASH_HOST: "localhost:5000"
      DEV_SERVER_HOST: "0.0.0.0"
      SERVER_NAME: "localhost"
      REDASH_MAIL_DEFAULT_SENDER: redash@example.com
      REDASH_MAIL_SERVER: email
  scheduler:
    build: .
    command: dev_scheduler
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - server
    environment:
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_MAIL_DEFAULT_SENDER: redash@example.com
      REDASH_MAIL_SERVER: email
  worker:
    build: .
    command: dev_worker
    volumes:
      - type: bind
        source: .
        target: /app
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres@postgres/postgres"
      REDASH_MAIL_DEFAULT_SENDER: redash@example.com
      REDASH_MAIL_SERVER: email
  redis:
    image: redis:3.0-alpine
    restart: unless-stopped
  postgres:
    image: postgres:9.5-alpine
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    ports:
      - "15432:5432"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  email:
    image: djfarrelly/maildev
    ports:
      - "1080:80"
    restart: unless-stopped

volumes:
  node_modules:
  python_local:
  home_cache:
  client_dist:
